//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Books
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderBookId { get; set; }
        public int OrderSubsId { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Sub Sub { get; set; }
    }
}
